---
- hosts: webservers
  gather_facts: no
  vars:
    user: "{{ ansible_user }}"
    project_name: gwent_website
    dadata_api_key: "{{ lookup('env', 'DADATA_API_KEY') }}"
    debug: "{{ lookup('env', 'DEBUG') }}"
    production: "{{ lookup('env', 'PRODUCTION') }}"
    external_media_storage: "{{ lookup('env', 'EXTERNAL_MEDIA_STORAGE') }}"
    secret_key: "{{ lookup('env', 'SECRET_KEY') }}"
    yookassa_secret_key: "{{ lookup('env', 'YOOKASSA_SECRET_KEY') }}"
    yookassa_shop_id: "{{ lookup('env', 'YOOKASSA_SHOP_ID') }}"
    database_url: "{{ lookup('env', 'DATABASE_URL') }}"
    admin_sdk: "{{ lookup('env', 'ADMIN_SDK') }}"
    url_sdk_storage: "{{ lookup('env', 'URL_SDK_STORAGE') }}"
    ngrok_authtoken: "{{ lookup('env', 'NGROK_AUTHTOKEN') }}"
    phone_number: "{{ lookup('env', 'PHONE_NUMBER') }}"
    email_address: "{{ lookup('env', 'EMAIL_ADDRESS') }}"

  tasks:
    - name: Ensure the latest code is pulled from GitHub
      git:
      # Для публичных репозиториев можно использовать http
      # что бы не добавлять ssh ключи на сервер
        repo: "https://github.com/Asgef/{{ project_name }}.git"
        dest: "/home/{{ user }}/{{ project_name }}"
        version: main
        update: yes
      
    - name: Add .env file
      ansible.builtin.template:
        src: ".env.j2"
        dest: "/home/{{ user }}/{{ project_name }}/.env"

    - name: Show shell
      ansible.builtin.shell: |
        asdf
        echo $SHELL
      register: asdf_processes
      ignore_errors: true

    - name: Debug Gunicorn processes
      ansible.builtin.debug:
        var: asdf_processes

    - name: Install project
      ansible.builtin.command: |
        make install
      args:
        chdir: "/home/{{ user }}/{{ project_name }}"

    - name: Build project
      ansible.builtin.shell: |
        make build
      args:
        chdir: "/home/{{ user }}/{{ project_name }}"

    - name: Stop any running Gunicorn processes
      ansible.builtin.shell: make stop-production
      args:
        chdir: "/home/{{ user }}/{{ project_name }}"
      ignore_errors: true

#    - name: Start the project
#      ansible.builtin.shell: |
#        export ASDF_DIR=$HOME/.asdf
#        . $HOME/.asdf/asdf.sh
#        export PATH="$HOME/.asdf/shims:$HOME/.asdf/bin:$PATH"
#        make start-production
#      args:
#        chdir: "/home/{{ user }}/{{ project_name }}"


