# Generated by Django 5.0.6 on 2024-06-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/game_gwent/catalog/img/', verbose_name='Изображение'),
        ),
    ]
