# Generated by Django 5.0.6 on 2024-06-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_image_product_main_image_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Галерея'},
        ),
    ]
