# Generated by Django 5.0.6 on 2024-09-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_productimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='game_gwent/catalog/img/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='game_gwent/catalog/img/', verbose_name='Изображения'),
        ),
    ]
