# Generated by Django 5.0.6 on 2024-07-05 13:16

import game_gwent.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(max_length=100, verbose_name='Область'),
        ),
    ]
