name: Deploy Django Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install ansible

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
        run: |
          ansible-playbook -i hosts.ini deploy.yml
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
